apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- deployment.yaml

namespace: main
images:
- name: goserver
  newName: lucasfernandesapp/fc
  newTag: 02557b15bdd20d99669afc1c31f6c0675df9a705
